Repository concert-crew/client, pull requests merged in 2022-10, with the labels that each got.

#11 Jm/user dashboard v1
  docs/pull-request-template.md
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/EventCard/EventCard.js
  src/components/EventsContainer/EventsContainer.js
  src/components/Login/Login.js
  src/components/UserDashboard/UserDashboard.js
  src/index.js
  src/sampleUser.js
Labels: documentation, enhancement, initial build

#13 Feat: add icons
  src/images/GH.svg
  src/images/IG.svg
  src/images/LI.svg
  src/images/add-friend.svg
  src/images/delete-friend.svg
  src/images/exit-btn.svg
  src/images/friends_1.svg
  src/images/home-icon2.svg
  src/images/user-icon.svg
Labels: enhancement, UI/UX

#15 Jm/comment section
  package-lock.json
  package.json
  src/EventDetails/EventDetails.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/EventCard/EventCard.js
  src/components/EventsContainer/EventsContainer.js
  src/components/FriendsDashboard/FriendsDashboard.js
  src/components/Header/Header.js
  src/components/Login/Login.js
  src/components/UserDashboard/UserDashboard.js
  src/sampleUser.js
Labels: enhancement, UI/UX

#20 Cg/refactor scroll bug
  package-lock.json
  package.json
  public/index.html
  src/EventDetails/EventDetails.css
  src/EventDetails/EventDetails.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/EventCard/EventCard.js
  src/components/EventsContainer/EventsContainer.css
  src/components/FriendsDashboard/FriendsDashboard.css
  src/components/FriendsDashboard/FriendsDashboard.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/components/UserDashboard/UserDashboard.css
  src/components/UserDashboard/UserDashboard.js
  src/errorHandling/InternalServerError.css
  src/errorHandling/InternalServerError.js
  src/errorHandling/Status.js
  src/errorHandling/Status404.css
  src/errorHandling/Status404.js
  src/images/error404-background.png
  src/index.css
Labels: refactor

#16 Feat: format scroll animation to user and friends dash
  package-lock.json
  package.json
  public/index.html
  src/components/App/App.css
  src/components/App/App.js
  src/components/EventCard/EventCard.js
  src/components/EventsContainer/EventsContainer.css
  src/components/FriendsDashboard/FriendsDashboard.css
  src/components/FriendsDashboard/FriendsDashboard.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/components/UserDashboard/UserDashboard.css
  src/components/UserDashboard/UserDashboard.js
  src/index.css
Labels: enhancement, UI/UX

#23 Cg/search form
  src/components/App/App.js
  src/components/SearchEventsContainer/SearchEventsContainer.css
  src/components/SearchEventsContainer/SearchEventsContainer.js
  src/components/SearchForm/SearchForm.css
  src/components/SearchForm/SearchForm.js
  src/components/UserDashboard/UserDashboard.js
Labels: enhancement, API, form

#27 Cg/404 design
  public/favicon.ico
  public/index.html
  src/components/App/App.js
  src/components/EventDetails/EventDetails.css
  src/components/EventDetails/EventDetails.js
  src/components/SearchEventsContainer/SearchEventsContainer.js
  src/components/UserDashboard/UserDashboard.js
  src/errorHandling/Status404.css
  src/errorHandling/Status404.js
  src/images/logos/cc-favicon-mint.png
  src/images/logos/cc-favicon-mint.svg
  src/images/logos/cc-favicon-pink-bold.png
  src/images/logos/cc-favicon-pink-bold.svg
  src/images/logos/cc-favicon-pink.svg
  src/images/logos/cc-favicon-white.svg
  src/images/logos/cc-logo.svg
  src/images/logos/favicon-lg-pink.png
  src/images/logos/favicon-lg-pink.svg
Labels: enhancement, UI/UX, error-handling

#30 Refactor: fix ID key
  src/components/App/App.js
  src/components/EventDetails/EventDetails.js
  src/components/EventsContainer/EventsContainer.js
  src/components/Login/Login.js
  src/components/SearchEventsContainer/SearchEventsContainer.css
  src/components/SearchEventsContainer/SearchEventsContainer.js
  src/components/SearchForm/SearchForm.js
  src/components/UserDashboard/UserDashboard.js
Labels: enhancement, good first issue, med-priority, refactor, API

#34 Feat: add pink logo-spin component
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/SpinLogo/SpinLogo.css
  src/components/SpinLogo/SpinLogo.js
  src/components/UserDashboard/UserDashboard.js
  src/errorHandling/Status404.js
Labels: enhancement, UI/UX, error-handling

#35 Refactor: display attendees
  src/components/App/App.css
  src/components/App/App.js
  src/components/EventDetails/EventDetails.js
  src/components/EventsContainer/EventsContainer.js
  src/components/FriendsDashboard/FriendsDashboard.js
  src/components/Header/Header.js
  src/components/Login/Login.js
  src/components/Mutation/Mutation.js
  src/components/UserDashboard/UserDashboard.js
  src/hooks/useUser.js
Labels: enhancement, refactor

#37 Jm/troubleshooting v2
  .circleci/config.yml
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/components/App/App.test.js
  src/components/EventCard/EventCard.js
  src/components/EventDetails/EventDetails.js
  src/components/SearchForm/SearchForm.js
Labels: testing

#39 Al/feat/cypress
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/user.json
  src/components/FriendsDashboard/FriendsDashboard.css
  src/components/FriendsDashboard/FriendsDashboard.js
  src/components/Header/Header.css
  src/components/UserDashboard/UserDashboard.css
Labels: testing

#42 Jm/mutation refactor
  cypress/support/commands.js
  package.json
  src/components/App/App.js
  src/components/EventCard/EventCard.css
  src/components/EventCard/EventCard.js
  src/components/EventDetails/EventDetails.css
  src/components/EventDetails/EventDetails.js
  src/components/EventsContainer/EventsContainer.css
  src/components/EventsContainer/EventsContainer.js
  src/components/FriendsDashboard/FriendsDashboard.css
  src/components/FriendsDashboard/FriendsDashboard.js
  src/components/Header/Header.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/components/Mutation/Mutation.js
  src/components/SearchForm/SearchForm.css
  src/components/SearchForm/SearchForm.js
  src/components/SpinLogo/SpinLogo.css
  src/components/SpinLogo/SpinLogo.js
  src/components/UserDashboard/UserDashboard.css
  src/components/UserDashboard/UserDashboard.js
  src/errorHandling/InternalServerError.css
  src/errorHandling/InternalServerError.js
  src/errorHandling/Status.js
  src/errorHandling/Status404.css
  src/errorHandling/Status404.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/sampleEvents.js
  src/sampleUser.js
  src/utilities/fetchEvent.js
  src/utilities/hooks/useUser.js
Labels: enhancement, UI/UX, error-handling, refactor
